### ISSUE TITLE
Sync is very, very slow.

### ISSUE THREAD

**Issue by eperdeme** [containers/skopeo#1021]
Hello,

Does anybody have any thoughts on how to speed up a sync. We mirror a lot of external repos on mass for all versions and the process can take several hours layer by layer, tag by tag, repo by repo.

Is there anyway to parallel to run for every repo ? I've thought about maybe splitting each external repo in to separate yamls and run more skopeo commands at same time.

```
skopeo --insecure-policy sync --src yaml --dest docker src_mirrors.yaml dest.internal.repo/mirrors/ --scoped --dest-creds X:X

docker.io:
    images:
        istio/proxyv2: []
        sergrua/kube-tagger: []
        splunk/fluentd-hec: []
        hazelcast/management-center: []
        k8srestdev/scaling: []
        hjacobs/kube-resource-report: []
        tutum/dnsutils: []
        bitnami/external-dns: []
        falcosecurity/falco: []
        praqma/helmsman: []
        weaveworks/flagger: []
        weaveworks/flagger-loadtester: []
quay.io:
    images:
        coreos/prometheus-config-reloader: []
        prometheus/prometheus: []
        prometheus/alertmanager: []
        prometheus/node-exporter: []
        kiali/kiali: []
        coreos/configmap-reload: []
        coreos/prometheus-operator: []
        thanos/thanos: []
        calico/node: []
        coreos/kube-state-metrics: []
        calico/typha: []
        external_storage/efs-provisioner: []
gcr.io:
    images: 
        kubernetes-helm/tiller: []
        google_containers/busybox: []
        k8s-artifacts-prod/autoscaling: []
k8s.gcr.io:
    images:
        cluster-proportional-autoscaler-amd64: []
        metrics-server-amd64: [] 
```
