### ISSUE TITLE
list-tags ignores mirrors?

### ISSUE THREAD

**Issue by AstraLuma** [containers/skopeo#1050]
Running `skopeo list-tags docker://debian`, v1.1.1 on Ubuntu 18.04

`/etc/containers/registries.conf`:

```toml
unqualified-search-registries = ['mirror1.redacted', 'mirror2.redacted']

[[registry]]
prefix = "docker.io"
# location =  "registry-1.docker.io"
location = "mirror1.redacted"

[[registry.mirror]]
location = "mirror1.redacted"

[[registry.mirror]]
location = "mirror2.redacted"
```

I have set a similar configuration in `/etc/docker/daemon.json`.

(both mirrors are running `registry:2` set in proxy/mirror mode)

If I override `registry-1.docker.io` in `/etc/hosts`, I get this:

```
FATA[0060] Error listing repository tags: error pinging docker registry registry-1.docker.io: Get https://registry-1.docker.io/v2/: dial tcp 192.0.2.0:443: i/o timeout
```

This would strongly indicate that `list-tags` is ignoring my registry settings?

I'm getting the same error for `docker://library/debian` and `docker://docker.io/library/debian`
