### ISSUE TITLE
skopeo copy fails when using --src-creds and --dest-creds directly

### ISSUE THREAD

**Issue by wonderfulspam** [containers/skopeo#1315]
This bug seems to have been introduced in 1.3.0. 1.2.1 works fine.

The following command:

```
skopeo copy --src-creds=<creds> --dest-creds=<creds> "docker://<path_to_src_image>" "docker://<path_to_dest_image>"
```

produces the following error:
> Error loading trust policy: open /etc/containers/policy.json: no such file or directory

The error occurred in a Gitlab CI/CD pipeline using alpine. Job spec:

```yaml
Release image:
    stage: release
    image: alpine
    before_script:
        - apk add skopeo
    script:
        - skopeo copy
            --src-creds=${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
            --dest-creds=${RELEASE_REGISTRY_USER}:${RELEASE_REGISTRY_PASSWORD}
            "docker://${IMAGE_SHA}"
            "docker://${IMAGE_LATEST}"
```

Downgrading to alpine 3.13 and skopeo 1.2.1 fixes the issue:
```yaml
Release image:
    stage: release
    image: alpine:3.13
    before_script:
        - apk add skopeo=1.2.1-r0
    script:
        - skopeo copy
            --src-creds=${CI_REGISTRY_USER}:${CI_BUILD_TOKEN}
            --dest-creds=${RELEASE_REGISTRY_USER}:${RELEASE_REGISTRY_PASSWORD}
            "docker://${IMAGE_SHA}"
            "docker://${IMAGE_LATEST}"
```

Not sure if this is caused by https://github.com/containers/skopeo/commit/c84fc7d2434d09e75fe1cdfdcb7333f5bdbaea1c which was the one thing in the 1.3.0 changelog that seemed potentially relevant.
