### ISSUE TITLE
Using skopen in github actions

### ISSUE THREAD

**Issue by lburgazzoli** [containers/skopeo#1654]
I have a [very simple action](https://github.com/lburgazzoli/lb-actions-playground/blob/master/.github/workflows/playground.yml) to test how to use skopeo in a GitHub Action

```yaml
name: run
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  kustomize:
    runs-on: ubuntu-22.04
    steps:
      - name: "Skopeo"
        run: |    
          skopeo --version
          skopeo inspect docker://busybox:latest
```

When running the action, skopeo fails with the following error:

```
time="2022-05-25T21:0[7](https://github.com/lburgazzoli/lb-actions-playground/runs/6600214480?check_suite_focus=true#step:2:8):37Z" 
level=fatal 
msg="Error parsing image name \"docker://busybox:latest\": getting username and password: 1 error occurred:\n\t* reading JSON file \"/run/containers/1001/auth.json\": open /run/containers/1001/auth.json: permission denied\n\n"
```

Note that the version provided by the runner is  1.4.1
