### ISSUE TITLE
sync

### ISSUE THREAD

**Issue by SamStenton** [containers/skopeo#1755]
```
registry.example.com:
    images:
        busybox: []
        redis:
            - ">1.0"
    images-by-tag-regex:
        nginx: ^1\.13\.[12]-alpine-perl$
```
