### ISSUE TITLE
sync all images from a starting version

### ISSUE THREAD

**Issue by SamStenton** [containers/skopeo#1756]
It would be beneficial to be able to define a minimum version to sync against so that all versions above that initial definition are copied.

We're running Skopeo on a schedule to move images from one repo to another, I don't want to copy all images ever created but instead copy all images created that are greater than a defined version. 

This might look like this when using the yaml config: 

```yaml
docker.io:
    images:
        busybox:
            - "~1.0.0" # Sync all patch tags
            - "^1.0.0" # Sync all minor and patch tags
            - ">1.1.5" # Sync all tags above and including 1.1.5
```

I know this can be achieved using the regex method however the readability of that begins to get pretty difficult and importantly it's really easy to miss edge cases. 

```yaml
docker.io:
    images-by-tag-regex:
        jetstack/cert-manager-webhook: (v1\.[8-9]\.[0-9]+$)|v([2-9]+)\.([0-9]+)\.[0-9]+$ # match anything above 1.8.0 (various edge cases that get missed, like v1.10.0
        jetstack/cert-manager-webhook: (v1\.[8-9]\.[0-9]+$)|v([2-9]+)\.([0-9]+)\.[0-9]+$
        istio/proxyv2: ([0-9])\.([1-9][3-9]|[2-9][0-9])\.[0-9]*$ # match anything starting from 1.13.0.
```
