### ISSUE TITLE
skopeo sync with src yaml, credentials get ignored in yaml

### ISSUE THREAD

**Issue by repi02** [containers/skopeo#1931]
We want to sync multiple images from nvidia catalog to our own registry using a yaml file a src. but it always ends with an "unauthenticated" error as if the credentials are not used.

```
FATA[0002] Error copying ref "docker://nvcr.io/gpu-operator-3-0:v22.9.1": initializing source docker://nvcr.io/gpu-operator-3-0:v22.9.1: reading manifest v22.9.1 in nvcr.io/gpu-operator-3-0: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

```

my yaml file looks like this with one example images we want to sync.

```
nvcr.io:
    images:
        gpu-operator-3-0:
            - "v22.9.1"
    credentials:
        username: $oauthtoken
        password: password
    tls-verify: false


```

this is the command we run:

`skopeo sync --src yaml --dest docker --dest-creds='username':<password> ./sync.yaml my-registry/nvidia`

using src=docker like this, with same user/password combination works without issue.

`skopeo sync --src docker --src-tls-verify=false --src-creds='$oauthtoken':<password> --dest docker --dest-creds='username':<password> nvcr.io/nvaie/gpu-operator-3-0:v22.9.1 my-registry/nvidia`
