### ISSUE TITLE
help: skopeo sync How to keep mirroring to project names

### ISSUE THREAD

**Issue by jinjianming** [containers/skopeo#1992]
For example mine : sync.yml 

```
 registry.js.design:
      images:
          justwatch/elasticsearch_exporter:
              - "1.1.0"
          elasticsearch/elasticsearch:
              - "7.8.1"
```
My Sync Command
```
skopeo sync --tls-verify=false --src yaml --dest docker sync.yml js-registry:5000/
```

My expected effect
```
js-registry:5000/justwatch/elasticsearch_exporter:1.1.0
js-registry:5000/elasticsearch/elasticsearch:7.8.1
```
Actual effect
```
js-registry:5000/elasticsearch_exporter:1.1.0
js-registry:5000/elasticsearch:7.8.1
```
