### ISSUE TITLE
How to preserve repository while archiving image?

### ISSUE THREAD

**Issue by davidfrickert** [containers/skopeo#2370]
Looking to achieve the same output that `docker image save <image>` produces, without needing docker daemon running.

It seems that skopeo copy / sync even with --preserve-digests does not produce the same output, as original repository is lost in the image manifests of the tar produced by skopeo.

If I inspect some files of the generated tar, there is for example index.json which is not present in the tar generated by skopeo, contains some annotations with the repo.

```
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:98bfb335ba4018e9307da07ee15eddab804022830f4f5fc8a0d664075be66c52",
      "size": 552,
      "annotations": {
        "io.containerd.image.name": "<jfrog>/<jfrog-repo>/alpine/openssl:latest",
        "org.opencontainers.image.ref.name": "latest"
      }
    }
  ]
}
```

Also, manifest.json generated by the docker command contains:
```
    "RepoTags": [
      "<jfrog>/<jfrog-repo>/alpine/openssl:latest"
    ]
```

While the manifest.json generated by skopeo contains:

```
    "RepoTags": [

    ]
```

This means that when trying to push these images to a docker registry while preserving the repository, it fails since the images do not have the original repository anywhere, e.g.:

```
# --> only works if TAR files have been generated from docker image save and not skopeo
- name: Push images to a local private registry
  community.docker.docker_image:
    name: "{{ item.repository }}{{ item.name }}"
    repository: "{{ hostvars[groups['repo_nodes'][0]].ansible_host }}:{{ private_registry_port }}/{{ item.repository }}{{ item.name }}:{{ item.tag }}"
    tag: "{{ item.tag }}"
    #force_tag: true
    push: true
    load_path: "{{ images_dir }}/{{ item.name | replace('/','_') }}_{{ item.tag }}.tar"
    source: load
  with_items: "{{ docker_images }}"
  register: push_result
```

Any way to preserve this such that the above ansible command works with the images generated by skopeo? 
Tried a few combinations already of copy, sync, --preserve-digests, --all, no luck.
