### ISSUE TITLE
Skopeo copy - Error during unshare(...) Operation not permitted

### ISSUE THREAD

**Issue by Raboo** [containers/skopeo#2377]
Hi I'm running skopeo copy in a github actions runner that is using `runs-on: ubuntu-24.04`.

My copy command is producing an error.
```
skopeo copy containers-storage:ghcr.io/raboo/redir:build-amd64 oci-archive:/tmp/amd64-oci.tar
Error during unshare(...): Operation not permitted
```

Trying to copy a image that is built using buildah.
This unshare error doesn't tell much. Is there a problem when reading from containers-storage or when making a new OCI tarball or when writing it to /tmp?
How do I fix this?

Thanks

**Comment by mtrmac** [comment]
Thanks for reaching out.

That’s happening when switching to a user namespace in order to access the `containers-storage` location. If Buildah is running _in the same environment_, I‘d expect the environment to be allowing the operation.

The error is reported from a direct system call, so there probably isn’t much more specific information than the EPERM reported.

**Comment by Raboo** [comment]
Should be same namespace.
This is pretty much what I'm doing in github actions.

```yaml
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: redir
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        oci: true
        containerfiles: |
          ./Containerfile
        platforms: ${{ matrix.platform }}

    - run: skopeo copy containers-storage:ghcr.io/${{ env.OWNER_LC }}/redir:build-${{ env.PODMAN_ARCH }} oci-archive:/tmp/${{ env.PODMAN_ARCH }}-oci.tar

```
