### ISSUE TITLE
Image Paths are not evaluated correctly when attempting a skopeo sync to another GitLab Instance

### ISSUE THREAD

**Issue by justinreddick** [containers/skopeo#2461]
When trying to sync to another gitlab registry there was an issue encountered where the image path was not parsed correctly by skopeo. A longer image path will cause an error when attempting to sync.

```
customgitlab.example.com:
    images:
        gitlabgroup/repo/projectpath:
            - "latest"
```

The above will cause an error and skopeo will evaluate the above with `customgitlab.example.com/projectpath:latest` instead of the provided path for the image `(customgitlab.example.com/gitlabgroup/repo/projectpath:latest)`.
