### ISSUE TITLE
Avoid copy of existing layers

### ISSUE THREAD

**Issue by nlewo** [containers/skopeo#511]
When copying an image from a Docker daemon to a local Docker registry, existing layer are copyied even if they already exists on the destination.
This is not the behavior of the Docker pull command.

Is this an expected behavior?

**Comment by runcom** [comment]
dup of https://github.com/projectatomic/skopeo/issues/395 and https://github.com/projectatomic/skopeo/issues/281

**Comment by nlewo** [comment]
Ok, thanks.
So, it seems it is because layers are compressed on the fly, so we cannot know the sha before the upload. 
If it is true, do you know how docker does?

**Comment by mtrmac** [comment]
It keeps a local ~cache of compressed digest ↔︎ uncompressed digest correspondences; so, it can detect that the compressed equivalent is already stored on a registry, or that a decompressed layer is already available locally.

**Comment by nlewo** [comment]
hmm... so there is a bug then :/ because this is not the behavior I'm observing.

**Comment by abergmeier** [comment]
Dumb question but is there really no way of not copying when dest is already up to date? That makes Skopeo unusable for us.

**Comment by TomSweeneyRedHat** [comment]
@abergmeier I don't believe there is currently a way to copy and skip layers/images already locally stored with Skopeo.  But that does seem like a nice feature, something like `podman build --pull=false..`  where the image is pulled only if it isn't already present?  Perhaps a new `--copy-if-needed` option that could be used instead of `--copy`.  I'm going to reopen this and I'm sure @mtrmac or @vrothberg will have further insights/thoughts.

**Comment by abergmeier** [comment]
For CloudBuild I now solved this by going back to using docker:

```
steps:
  - id: Warm up local docker cache
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
    - '-c'
    - |
      docker pull eu.gcr.io/test/maven:3.6.3-openjdk-14 || exit 0
  - id: Pull latest maven image
    name: gcr.io/cloud-builders/docker
    args:
    - pull
    - maven:3.6.3-openjdk-14
  - id: Set local maven image to latest state
    name: gcr.io/cloud-builders/docker
    args:
    - tag
    - maven:3.6.3-openjdk-14
    - eu.gcr.io/test/maven:3.6.3-openjdk-14
  - id: Populate cached maven image
    name: gcr.io/cloud-builders/docker
    args:
    - push
    - eu.gcr.io/test/maven:3.6.3-openjdk-14
```

and docker is smart enough to do the "minimum" amount of data transfering.
