### ISSUE TITLE
Cannot use skopeo sync with digests

### ISSUE THREAD

**Issue by muff1nman** [containers/skopeo#858]
The following are all unsupported with skopeo sync with the yaml source format:
```
docker.io:
  images:
    rook/ceph:
      - "sha256:abd9b6b6c356958eead449869f6a75f6e47e1d04d7bfc7bde69d87319e5fbf61"
```
```
docker.io:
  images:
    rook/ceph:
      - "v1.2.4@sha256:abd9b6b6c356958eead449869f6a75f6e47e1d04d7bfc7bde69d87319e5fbf61"
```
```
docker.io:
  images:
    rook/ceph:
      - "@sha256:abd9b6b6c356958eead449869f6a75f6e47e1d04d7bfc7bde69d87319e5fbf61"
```

Is supporting digests in the yaml source something skopeo is open to receiving a patch for?
